### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by akbarjondev** [Muhammadboburshoh/todo-list#2]
![Screenshot_2020-11-10 Muhammadboburshoh todo-list](https://user-images.githubusercontent.com/36984628/98634473-34c56780-2345-11eb-8b68-5d53032b896d.png)
29-qatordagi kodni 32-qatorga tushirib, 32-qatordagi `console.log()` ni olib tashlang.

**Comment by Muhammadboburshoh** [comment]
to'girlandi :)
